//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Pattern {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Pattern() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.Pattern", typeof(Pattern).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amounts less than {0} Toman cannot be paid..
        /// </summary>
        public static string AmountsLessT1CannotPaid {
            get {
                return ResourceManager.GetString("AmountsLessT1CannotPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course ({0}) is a prerequisite for this course.
        /// </summary>
        public static string CourseT1IsPrerequisiteForThisCourse {
            get {
                return ResourceManager.GetString("CourseT1IsPrerequisiteForThisCourse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping in the next {0} days.
        /// </summary>
        public static string DeliveryDays {
            get {
                return ResourceManager.GetString("DeliveryDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} must be at least {1} number.
        /// </summary>
        public static string NumberEnteredMustLeastNumber {
            get {
                return ResourceManager.GetString("NumberEnteredMustLeastNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment of invoice number {0}.
        /// </summary>
        public static string PaymentDescription {
            get {
                return ResourceManager.GetString("PaymentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert the {0}.
        /// </summary>
        public static string PleaseInsertT1 {
            get {
                return ResourceManager.GetString("PleaseInsertT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select the {0}.
        /// </summary>
        public static string PleaseSelectT1 {
            get {
                return ResourceManager.GetString("PleaseSelectT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} با شماره پیگیری {1}.
        /// </summary>
        public static string ProductOrderTrakingCode {
            get {
                return ResourceManager.GetString("ProductOrderTrakingCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pastil.
        /// </summary>
        public static string Push_Title {
            get {
                return ResourceManager.GetString("Push_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer {0} canceled their {1} reservation.
        /// </summary>
        public static string PushCancelReserveCompanion {
            get {
                return ResourceManager.GetString("PushCancelReserveCompanion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0}, Your reservation for {1} has been canceled.
        /// </summary>
        public static string PushCancelReserveUser {
            get {
                return ResourceManager.GetString("PushCancelReserveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0}, Your reservation has been completed.
        /// </summary>
        public static string PushCompleteReserveUser {
            get {
                return ResourceManager.GetString("PushCompleteReserveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0}, Your Order with order number {1} is Processing..
        /// </summary>
        public static string PushProccessOrderUser {
            get {
                return ResourceManager.GetString("PushProccessOrderUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0}, Your order with order number {1} has been registered.
        /// </summary>
        public static string PushRegisterOrderUser {
            get {
                return ResourceManager.GetString("PushRegisterOrderUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a new reservation from {0}..
        /// </summary>
        public static string PushRegisterPansionCompanion {
            get {
                return ResourceManager.GetString("PushRegisterPansionCompanion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0}, You have Reserved {1} Pension..
        /// </summary>
        public static string PushRegisterPansionUser {
            get {
                return ResourceManager.GetString("PushRegisterPansionUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have a new reservation from {0} for {1}.
        /// </summary>
        public static string PushRegisterReserveCompanion {
            get {
                return ResourceManager.GetString("PushRegisterReserveCompanion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0}, {1} has been reserved for your pet..
        /// </summary>
        public static string PushRegisterReserveUser {
            get {
                return ResourceManager.GetString("PushRegisterReserveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0}, Your order {1} has been sent.
        /// </summary>
        public static string PushSentOrderUser {
            get {
                return ResourceManager.GetString("PushSentOrderUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0}, Welcome Back to Pastil.
        /// </summary>
        public static string PushSignInUser {
            get {
                return ResourceManager.GetString("PushSignInUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear {0}, Welcome to Pastil.
        /// </summary>
        public static string PushSignUpUser {
            get {
                return ResourceManager.GetString("PushSignUpUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حداقل مبلغ سفارش باید {0} باشد.
        /// </summary>
        public static string RebateMinCartPrice {
            get {
                return ResourceManager.GetString("RebateMinCartPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to entering the wrong code more than three times, resending is not possible until {0} minutes later.
        /// </summary>
        public static string WrongVrifyCodeCount {
            get {
                return ResourceManager.GetString("WrongVrifyCodeCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما می توانید حداکثر {0} عدد از این محصول را خریداری کنید.
        /// </summary>
        public static string YouCanBuyUpToT1Product {
            get {
                return ResourceManager.GetString("YouCanBuyUpToT1Product", resourceCulture);
            }
        }
    }
}
