USE [pastil_db]
GO
-- نژادهای سگ - ادامه‌ی لیست موجود (۵۸ نژاد قبلی دست نخورده می‌مونه)
-- IDها اتوماتیک (IDENTITY) تخصیص داده می‌شن، نیازی به IDENTITY_INSERT نیست.

INSERT INTO [dbo].[PetBreeds] ([PetId], [Label], [PictureId], [Priority], [Deleted], [Name], [Slug]) VALUES
-- Sporting / Gundogs
(1, N'Weimaraner', NULL, 59, 0, N'وایمارانر', N'weimaraner'),
(1, N'Vizsla', NULL, 60, 0, N'ویزلا', N'vizsla'),
(1, N'German Shorthaired Pointer', NULL, 61, 0, N'پوینتر آلمانی موکوتاه', N'german-shorthaired-pointer'),
(1, N'German Wirehaired Pointer', NULL, 62, 0, N'پوینتر آلمانی موسیم', N'german-wirehaired-pointer'),
(1, N'Brittany', NULL, 63, 0, N'بریتانی', N'brittany'),
(1, N'Flat-Coated Retriever', NULL, 64, 0, N'رتریور موصاف', N'flat-coated-retriever'),
(1, N'Curly-Coated Retriever', NULL, 65, 0, N'رتریور موفرفری', N'curly-coated-retriever'),
(1, N'Chesapeake Bay Retriever', NULL, 66, 0, N'رتریور خلیج چساپیک', N'chesapeake-bay-retriever'),
(1, N'Nova Scotia Duck Tolling Retriever', NULL, 67, 0, N'تولر نواسکوشیا', N'nova-scotia-duck-tolling-retriever'),
(1, N'Irish Water Spaniel', NULL, 68, 0, N'اسپانیل آبی ایرلندی', N'irish-water-spaniel'),
(1, N'Clumber Spaniel', NULL, 69, 0, N'کلامبر اسپانیل', N'clumber-spaniel'),
(1, N'Field Spaniel', NULL, 70, 0, N'فیلد اسپانیل', N'field-spaniel'),
(1, N'Sussex Spaniel', NULL, 71, 0, N'ساسکس اسپانیل', N'sussex-spaniel'),
(1, N'Welsh Springer Spaniel', NULL, 72, 0, N'اسپرینگر اسپانیل ولزی', N'welsh-springer-spaniel'),
(1, N'Gordon Setter', NULL, 73, 0, N'گوردون ستر', N'gordon-setter'),
(1, N'English Setter', NULL, 74, 0, N'انگلیش ستر', N'english-setter'),
(1, N'Wirehaired Pointing Griffon', NULL, 75, 0, N'گریفون موسیم', N'wirehaired-pointing-griffon'),
(1, N'Spinone Italiano', NULL, 76, 0, N'اسپینونه ایتالیایی', N'spinone-italiano'),
(1, N'Portuguese Water Dog', NULL, 77, 0, N'سگ آبی پرتغالی', N'portuguese-water-dog'),

-- Hounds
(1, N'Basenji', NULL, 78, 0, N'باسنجی', N'basenji'),
(1, N'Rhodesian Ridgeback', NULL, 79, 0, N'رودزین ریج‌بک', N'rhodesian-ridgeback'),
(1, N'Norwegian Elkhound', NULL, 80, 0, N'الک‌هوند نروژی', N'norwegian-elkhound'),
(1, N'Harrier', NULL, 81, 0, N'هریر', N'harrier'),
(1, N'American Foxhound', NULL, 82, 0, N'فاکس‌هوند آمریکایی', N'american-foxhound'),
(1, N'English Foxhound', NULL, 83, 0, N'فاکس‌هوند انگلیسی', N'english-foxhound'),
(1, N'Otterhound', NULL, 84, 0, N'اوتر‌هوند', N'otterhound'),
(1, N'Petit Basset Griffon Vendeen', NULL, 85, 0, N'پتی باست گریفون وندین', N'petit-basset-griffon-vendeen'),
(1, N'Ibizan Hound', NULL, 86, 0, N'ایبیزان هوند', N'ibizan-hound'),
(1, N'Pharaoh Hound', NULL, 87, 0, N'فرعون هوند', N'pharaoh-hound'),
(1, N'Norwegian Lundehund', NULL, 88, 0, N'لوندهوند نروژی', N'norwegian-lundehund'),
(1, N'Plott Hound', NULL, 89, 0, N'پلات هوند', N'plott-hound'),
(1, N'Black and Tan Coonhound', NULL, 90, 0, N'کون‌هوند مشکی و قهوه‌ای', N'black-and-tan-coonhound'),
(1, N'Bluetick Coonhound', NULL, 91, 0, N'بلوتیک کون‌هوند', N'bluetick-coonhound'),
(1, N'Redbone Coonhound', NULL, 92, 0, N'ردبون کون‌هوند', N'redbone-coonhound'),
(1, N'Treeing Walker Coonhound', NULL, 93, 0, N'تریینگ واکر کون‌هوند', N'treeing-walker-coonhound'),
(1, N'Borzoi', NULL, 94, 0, N'بورزوی', N'borzoi'),
(1, N'Irish Wolfhound', NULL, 95, 0, N'ولف‌هوند ایرلندی', N'irish-wolfhound'),
(1, N'Scottish Deerhound', NULL, 96, 0, N'دیرهوند اسکاتلندی', N'scottish-deerhound'),
(1, N'Azawakh', NULL, 97, 0, N'آزاواخ', N'azawakh'),
(1, N'Sloughi', NULL, 98, 0, N'اسلوقی', N'sloughi'),
(1, N'Galgo Espanol', NULL, 99, 0, N'گالگو اسپانیایی', N'galgo-espanol'),

-- Working
(1, N'Alaskan Klee Kai', NULL, 100, 0, N'آلاسکن کلی کای', N'alaskan-klee-kai'),
(1, N'Anatolian Shepherd', NULL, 101, 0, N'شپرد آناتولی', N'anatolian-shepherd'),
(1, N'Boerboel', NULL, 102, 0, N'بوئربول', N'boerboel'),
(1, N'Dogo Argentino', NULL, 103, 0, N'دوگو آرژانتینی', N'dogo-argentino'),
(1, N'Presa Canario', NULL, 104, 0, N'پرسا کاناریو', N'presa-canario'),
(1, N'Neapolitan Mastiff', NULL, 105, 0, N'ماستیف ناپولی', N'neapolitan-mastiff'),
(1, N'Bullmastiff', NULL, 106, 0, N'بول‌ماستیف', N'bullmastiff'),
(1, N'Leonberger', NULL, 107, 0, N'لئون‌برگر', N'leonberger'),
(1, N'Great Pyrenees', NULL, 108, 0, N'گریت پیرنیس', N'great-pyrenees'),
(1, N'Kuvasz', NULL, 109, 0, N'کوواس', N'kuvasz'),
(1, N'Komondor', NULL, 110, 0, N'کوموندور', N'komondor'),
(1, N'Akbash', NULL, 111, 0, N'آک‌باش', N'akbash'),
(1, N'Caucasian Shepherd Dog', NULL, 112, 0, N'سگ گله قفقازی', N'caucasian-shepherd-dog'),
(1, N'Central Asian Shepherd Dog', NULL, 113, 0, N'سگ گله آسیای مرکزی', N'central-asian-shepherd-dog'),
(1, N'Black Russian Terrier', NULL, 114, 0, N'تریر سیاه روسی', N'black-russian-terrier'),
(1, N'Dogue de Bordeaux', NULL, 115, 0, N'داگ دوبردو', N'dogue-de-bordeaux'),

-- Terriers
(1, N'Airedale Terrier', NULL, 116, 0, N'ایردیل تریر', N'airedale-terrier'),
(1, N'American Staffordshire Terrier', NULL, 117, 0, N'استافوردشایر تریر آمریکایی', N'american-staffordshire-terrier'),
(1, N'American Pit Bull Terrier', NULL, 118, 0, N'پیت‌بول تریر آمریکایی', N'american-pit-bull-terrier'),
(1, N'Staffordshire Bull Terrier', NULL, 119, 0, N'استافوردشایر بول‌تریر', N'staffordshire-bull-terrier'),
(1, N'West Highland White Terrier', NULL, 120, 0, N'وست‌های‌لند وایت تریر', N'west-highland-white-terrier'),
(1, N'Scottish Terrier', NULL, 121, 0, N'اسکاتیش تریر', N'scottish-terrier'),
(1, N'Cairn Terrier', NULL, 122, 0, N'کرن تریر', N'cairn-terrier'),
(1, N'Norfolk Terrier', NULL, 123, 0, N'نورفولک تریر', N'norfolk-terrier'),
(1, N'Norwich Terrier', NULL, 124, 0, N'نوریچ تریر', N'norwich-terrier'),
(1, N'Border Terrier', NULL, 125, 0, N'بردر تریر', N'border-terrier'),
(1, N'Wire Fox Terrier', NULL, 126, 0, N'فاکس تریر سیم‌مو', N'wire-fox-terrier'),
(1, N'Smooth Fox Terrier', NULL, 127, 0, N'فاکس تریر صاف‌مو', N'smooth-fox-terrier'),
(1, N'Lakeland Terrier', NULL, 128, 0, N'لیک‌لند تریر', N'lakeland-terrier'),
(1, N'Welsh Terrier', NULL, 129, 0, N'ولزی تریر', N'welsh-terrier'),
(1, N'Irish Terrier', NULL, 130, 0, N'ایریش تریر', N'irish-terrier'),
(1, N'Kerry Blue Terrier', NULL, 131, 0, N'کری بلو تریر', N'kerry-blue-terrier'),
(1, N'Soft Coated Wheaten Terrier', NULL, 132, 0, N'ویتن تریر موملایم', N'soft-coated-wheaten-terrier'),
(1, N'Manchester Terrier', NULL, 133, 0, N'منچستر تریر', N'manchester-terrier'),
(1, N'Bedlington Terrier', NULL, 134, 0, N'بدلینگتون تریر', N'bedlington-terrier'),
(1, N'Sealyham Terrier', NULL, 135, 0, N'سیلیهام تریر', N'sealyham-terrier'),
(1, N'Skye Terrier', NULL, 136, 0, N'اسکای تریر', N'skye-terrier'),
(1, N'Dandie Dinmont Terrier', NULL, 137, 0, N'دندی دینمونت تریر', N'dandie-dinmont-terrier'),
(1, N'Australian Terrier', NULL, 138, 0, N'استرالیایی تریر', N'australian-terrier'),
(1, N'Rat Terrier', NULL, 139, 0, N'رت تریر', N'rat-terrier'),
(1, N'Boston Terrier', NULL, 140, 0, N'بوستون تریر', N'boston-terrier'),
(1, N'Miniature Bull Terrier', NULL, 141, 0, N'بول‌تریر مینیاتوری', N'miniature-bull-terrier'),
(1, N'Parson Russell Terrier', NULL, 142, 0, N'پارسون راسل تریر', N'parson-russell-terrier'),

-- Toy
(1, N'Havanese', NULL, 143, 0, N'هاوانیز', N'havanese'),
(1, N'Japanese Chin', NULL, 144, 0, N'ژاپنی چین', N'japanese-chin'),
(1, N'Affenpinscher', NULL, 145, 0, N'آفن‌پینچر', N'affenpinscher'),
(1, N'Brussels Griffon', NULL, 146, 0, N'گریفون بروکسل', N'brussels-griffon'),
(1, N'English Toy Spaniel', NULL, 147, 0, N'اسپانیل اسباب‌بازی انگلیسی', N'english-toy-spaniel'),
(1, N'Italian Greyhound', NULL, 148, 0, N'گری‌هوند ایتالیایی', N'italian-greyhound'),
(1, N'Miniature Pinscher', NULL, 149, 0, N'پینچر مینیاتوری', N'miniature-pinscher'),
(1, N'Toy Fox Terrier', NULL, 150, 0, N'فاکس تریر اسباب‌بازی', N'toy-fox-terrier'),
(1, N'Chinese Crested', NULL, 151, 0, N'چاینیز کرستد', N'chinese-crested'),
(1, N'Coton de Tulear', NULL, 152, 0, N'کوتون دو تولیر', N'coton-de-tulear'),
(1, N'Silky Terrier', NULL, 153, 0, N'سیلکی تریر', N'silky-terrier'),
(1, N'Toy Poodle', NULL, 154, 0, N'پودل اسباب‌بازی', N'toy-poodle'),
(1, N'Miniature Poodle', NULL, 155, 0, N'پودل مینیاتوری', N'miniature-poodle'),

-- Herding
(1, N'Old English Sheepdog', NULL, 156, 0, N'سگ گله انگلیسی قدیم', N'old-english-sheepdog'),
(1, N'Bearded Collie', NULL, 157, 0, N'کولی ریشو', N'bearded-collie'),
(1, N'Rough Collie', NULL, 158, 0, N'کولی موبلند', N'rough-collie'),
(1, N'Smooth Collie', NULL, 159, 0, N'کولی موکوتاه', N'smooth-collie'),
(1, N'Shetland Sheepdog', NULL, 160, 0, N'شتلند شیپداگ', N'shetland-sheepdog'),
(1, N'Australian Cattle Dog', NULL, 161, 0, N'سگ گاو استرالیایی', N'australian-cattle-dog'),
(1, N'Belgian Tervuren', NULL, 162, 0, N'بلژیکی ترورن', N'belgian-tervuren'),
(1, N'Belgian Sheepdog', NULL, 163, 0, N'بلژیکی شیپداگ', N'belgian-sheepdog'),
(1, N'Belgian Laekenois', NULL, 164, 0, N'بلژیکی لکنوا', N'belgian-laekenois'),
(1, N'Bouvier des Flandres', NULL, 165, 0, N'بووی دِ فلاندر', N'bouvier-des-flandres'),
(1, N'Briard', NULL, 166, 0, N'بریارد', N'briard'),
(1, N'Icelandic Sheepdog', NULL, 167, 0, N'سگ گله ایسلندی', N'icelandic-sheepdog'),
(1, N'Finnish Lapphund', NULL, 168, 0, N'لاپ‌هوند فنلاندی', N'finnish-lapphund'),
(1, N'Swedish Vallhund', NULL, 169, 0, N'والهوند سوئدی', N'swedish-vallhund'),
(1, N'Polish Lowland Sheepdog', NULL, 170, 0, N'سگ گله لهستانی', N'polish-lowland-sheepdog'),
(1, N'Entlebucher Mountain Dog', NULL, 171, 0, N'سگ کوهستان انتلبوخر', N'entlebucher-mountain-dog'),
(1, N'Appenzeller Sennenhund', NULL, 172, 0, N'آپنزلر سنن‌هوند', N'appenzeller-sennenhund'),
(1, N'Greater Swiss Mountain Dog', NULL, 173, 0, N'سگ کوهستان سوئیسی بزرگ', N'greater-swiss-mountain-dog'),
(1, N'Canaan Dog', NULL, 174, 0, N'سگ کنعان', N'canaan-dog'),

-- Non-Sporting / Spitz / National breeds
(1, N'Lhasa Apso', NULL, 175, 0, N'لاسا آپسو', N'lhasa-apso'),
(1, N'Tibetan Terrier', NULL, 176, 0, N'تبتی تریر', N'tibetan-terrier'),
(1, N'Tibetan Spaniel', NULL, 177, 0, N'تبتی اسپانیل', N'tibetan-spaniel'),
(1, N'Keeshond', NULL, 178, 0, N'کیشوند', N'keeshond'),
(1, N'Schipperke', NULL, 179, 0, N'شیپرکی', N'schipperke'),
(1, N'Xoloitzcuintli', NULL, 180, 0, N'زولوایتسکوینتلی', N'xoloitzcuintli'),
(1, N'American Eskimo Dog', NULL, 181, 0, N'سگ اسکیمو آمریکایی', N'american-eskimo-dog'),
(1, N'Finnish Spitz', NULL, 182, 0, N'اسپیتز فنلاندی', N'finnish-spitz'),
(1, N'Norwegian Buhund', NULL, 183, 0, N'بوهوند نروژی', N'norwegian-buhund'),
(1, N'Lowchen', NULL, 184, 0, N'لوچن', N'lowchen'),
(1, N'Japanese Spitz', NULL, 185, 0, N'اسپیتز ژاپنی', N'japanese-spitz'),
(1, N'Volpino Italiano', NULL, 186, 0, N'ولپینو ایتالیایی', N'volpino-italiano'),
(1, N'Peruvian Inca Orchid', NULL, 187, 0, N'سگ اینکای پرو', N'peruvian-inca-orchid'),
(1, N'American Hairless Terrier', NULL, 188, 0, N'تریر بی‌موی آمریکایی', N'american-hairless-terrier'),
(1, N'Catahoula Leopard Dog', NULL, 189, 0, N'سگ پلنگی کاتاهولا', N'catahoula-leopard-dog'),
(1, N'Carolina Dog', NULL, 190, 0, N'سگ کارولینا', N'carolina-dog'),
(1, N'Chinook', NULL, 191, 0, N'چینوک', N'chinook'),
(1, N'American Bully', NULL, 192, 0, N'امریکن بولی', N'american-bully'),

-- Popular hybrid / designer breeds
(1, N'Labradoodle', NULL, 193, 0, N'لابرادودل', N'labradoodle'),
(1, N'Goldendoodle', NULL, 194, 0, N'گلدن‌دودل', N'goldendoodle'),
(1, N'Cockapoo', NULL, 195, 0, N'کوکاپو', N'cockapoo'),
(1, N'Maltipoo', NULL, 196, 0, N'مالتی‌پو', N'maltipoo'),
(1, N'Puggle', NULL, 197, 0, N'پاگل', N'puggle'),
(1, N'Schnoodle', NULL, 198, 0, N'اشنودل', N'schnoodle'),
(1, N'Yorkipoo', NULL, 199, 0, N'یورکی‌پو', N'yorkipoo'),
(1, N'Cavapoo', NULL, 200, 0, N'کاواپو', N'cavapoo'),
(1, N'Pomsky', NULL, 201, 0, N'پامسکی', N'pomsky');
GO
