USE [pastil_db]
GO
-- نژادهای پرنده - ادامه‌ی لیست موجود (۲۴ نژاد قبلی دست نخورده می‌مونه)

INSERT INTO [dbo].[PetBreeds] ([PetId], [Label], [PictureId], [Priority], [Deleted], [Name], [Slug]) VALUES
(4, N'Sun Conure', NULL, 25, 0, N'کانور آفتابی', N'sun-conure'),
(4, N'Green-Cheeked Conure', NULL, 26, 0, N'کانور گونه‌سبز', N'green-cheeked-conure'),
(4, N'Nanday Conure', NULL, 27, 0, N'کانور نندی', N'nanday-conure'),
(4, N'Blue and Gold Macaw', NULL, 28, 0, N'ماکائوی آبی و طلایی', N'blue-and-gold-macaw'),
(4, N'Scarlet Macaw', NULL, 29, 0, N'ماکائوی سرخ', N'scarlet-macaw'),
(4, N'Hyacinth Macaw', NULL, 30, 0, N'ماکائوی یاقوتی', N'hyacinth-macaw'),
(4, N'Military Macaw', NULL, 31, 0, N'ماکائوی نظامی', N'military-macaw'),
(4, N'Mini Macaw', NULL, 32, 0, N'ماکائوی کوچک', N'mini-macaw'),
(4, N'Umbrella Cockatoo', NULL, 33, 0, N'کاکادوی چتری', N'umbrella-cockatoo'),
(4, N'Sulphur-Crested Cockatoo', NULL, 34, 0, N'کاکادوی تاج‌گوگردی', N'sulphur-crested-cockatoo'),
(4, N'Moluccan Cockatoo', NULL, 35, 0, N'کاکادوی مولوکایی', N'moluccan-cockatoo'),
(4, N'Galah Cockatoo', NULL, 36, 0, N'کاکادوی گالا', N'galah-cockatoo'),
(4, N'Goffin s Cockatoo', NULL, 37, 0, N'کاکادوی گوفین', N'goffins-cockatoo'),
(4, N'Blue-Fronted Amazon', NULL, 38, 0, N'آمازون پیشانی‌آبی', N'blue-fronted-amazon'),
(4, N'Yellow-Naped Amazon', NULL, 39, 0, N'آمازون گردن‌زرد', N'yellow-naped-amazon'),
(4, N'Double Yellow-Headed Amazon', NULL, 40, 0, N'آمازون سرزرد', N'double-yellow-headed-amazon'),
(4, N'Meyer s Parrot', NULL, 41, 0, N'طوطی مایر', N'meyers-parrot'),
(4, N'Red-Bellied Parrot', NULL, 42, 0, N'طوطی شکم‌قرمز', N'red-bellied-parrot'),
(4, N'Pionus Parrot', NULL, 43, 0, N'طوطی پیونوس', N'pionus-parrot'),
(4, N'Hawk-Headed Parrot', NULL, 44, 0, N'طوطی سراشاهینی', N'hawk-headed-parrot'),
(4, N'White-Bellied Caique', NULL, 45, 0, N'کایک شکم‌سفید', N'white-bellied-caique'),
(4, N'Rainbow Lorikeet', NULL, 46, 0, N'لوریکیت رنگین‌کمانی', N'rainbow-lorikeet'),
(4, N'Plum-Headed Parakeet', NULL, 47, 0, N'پاراکیت سرآلویی', N'plum-headed-parakeet'),
(4, N'Derbyan Parakeet', NULL, 48, 0, N'پاراکیت دربیان', N'derbyan-parakeet'),
(4, N'Eastern Rosella', NULL, 49, 0, N'رزلای شرقی', N'eastern-rosella'),
(4, N'Kakariki', NULL, 50, 0, N'کاکاریکی', N'kakariki'),
(4, N'Gouldian Finch', NULL, 51, 0, N'فنچ گولدین', N'gouldian-finch'),
(4, N'Society Finch', NULL, 52, 0, N'فنچ اجتماعی', N'society-finch'),
(4, N'Star Finch', NULL, 53, 0, N'فنچ ستاره‌ای', N'star-finch'),
(4, N'Nutmeg Mannikin', NULL, 54, 0, N'فنچ جوز هندی', N'nutmeg-mannikin'),
(4, N'Diamond Firetail', NULL, 55, 0, N'فایرتیل الماسی', N'diamond-firetail'),
(4, N'Red Avadavat', NULL, 56, 0, N'آوادوات قرمز', N'red-avadavat'),
(4, N'Canary-Winged Parakeet', NULL, 57, 0, N'پاراکیت بال‌قناری', N'canary-winged-parakeet'),
(4, N'White-Eyed Conure', NULL, 58, 0, N'کانور چشم‌سفید', N'white-eyed-conure'),
(4, N'Hill Myna', NULL, 59, 0, N'مینای تپه‌ای', N'hill-myna'),
(4, N'Toco Toucan', NULL, 60, 0, N'توکان توکو', N'toco-toucan'),
(4, N'Fischer s Lovebird', NULL, 61, 0, N'مرغ عشق فیشر', N'fischers-lovebird'),
(4, N'Peach-Faced Lovebird', NULL, 62, 0, N'مرغ عشق صورتی', N'peach-faced-lovebird'),
(4, N'Masked Lovebird', NULL, 63, 0, N'مرغ عشق نقابدار', N'masked-lovebird'),
(4, N'Ringneck Dove', NULL, 64, 0, N'قمری یوغی', N'ringneck-dove'),
(4, N'Diamond Dove', NULL, 65, 0, N'قمری الماسی', N'diamond-dove'),
(4, N'Blue-Crowned Conure', NULL, 66, 0, N'کانور تاج‌آبی', N'blue-crowned-conure'),
(4, N'Patagonian Conure', NULL, 67, 0, N'کانور پاتاگونیایی', N'patagonian-conure'),
(4, N'Bourke s Parakeet', NULL, 68, 0, N'پاراکیت بورک', N'bourkes-parakeet'),
(4, N'Turquoise Parakeet', NULL, 69, 0, N'پاراکیت فیروزه‌ای', N'turquoise-parakeet');
GO
