USE [pastil_db]
GO
-- نژادهای گربه - ادامه‌ی لیست موجود (۳۳ نژاد قبلی دست نخورده می‌مونه)

INSERT INTO [dbo].[PetBreeds] ([PetId], [Label], [PictureId], [Priority], [Deleted], [Name], [Slug]) VALUES
(2, N'American Curl', NULL, 34, 0, N'امریکن کرل', N'american-curl'),
(2, N'American Bobtail', NULL, 35, 0, N'امریکن بابتیل', N'american-bobtail'),
(2, N'American Wirehair', NULL, 36, 0, N'امریکن وایرهیر', N'american-wirehair'),
(2, N'Australian Mist', NULL, 37, 0, N'استرالیایی میست', N'australian-mist'),
(2, N'Bambino', NULL, 38, 0, N'بامبینو', N'bambino'),
(2, N'Burmilla', NULL, 39, 0, N'برمیلا', N'burmilla'),
(2, N'Chantilly-Tiffany', NULL, 40, 0, N'شنتیلی-تیفانی', N'chantilly-tiffany'),
(2, N'Colorpoint Shorthair', NULL, 41, 0, N'کالرپوینت شورت‌هیر', N'colorpoint-shorthair'),
(2, N'Cymric', NULL, 42, 0, N'سیمریک', N'cymric'),
(2, N'Donskoy', NULL, 43, 0, N'دونسکوی', N'donskoy'),
(2, N'Dragon Li', NULL, 44, 0, N'دراگون لی', N'dragon-li'),
(2, N'Elf Cat', NULL, 45, 0, N'گربه الف', N'elf-cat'),
(2, N'European Shorthair', NULL, 46, 0, N'اروپایی شورت‌هیر', N'european-shorthair'),
(2, N'Foldex', NULL, 47, 0, N'فولدکس', N'foldex'),
(2, N'German Rex', NULL, 48, 0, N'جرمن رکس', N'german-rex'),
(2, N'Havana Brown', NULL, 49, 0, N'هاوانا براون', N'havana-brown'),
(2, N'Highlander', NULL, 50, 0, N'های‌لندر', N'highlander'),
(2, N'Japanese Bobtail', NULL, 51, 0, N'ژاپنی بابتیل', N'japanese-bobtail'),
(2, N'Javanese', NULL, 52, 0, N'جاوانیز', N'javanese'),
(2, N'Khao Manee', NULL, 53, 0, N'خائو مانی', N'khao-manee'),
(2, N'Korat', NULL, 54, 0, N'کورات', N'korat'),
(2, N'Kurilian Bobtail', NULL, 55, 0, N'کوریلیان بابتیل', N'kurilian-bobtail'),
(2, N'LaPerm', NULL, 56, 0, N'لاپرم', N'laperm'),
(2, N'Lykoi', NULL, 57, 0, N'لایکوی (گربه گرگ‌نما)', N'lykoi'),
(2, N'Minskin', NULL, 58, 0, N'مینسکین', N'minskin'),
(2, N'Munchkin', NULL, 59, 0, N'مانچکین', N'munchkin'),
(2, N'Nebelung', NULL, 60, 0, N'نبلونگ', N'nebelung'),
(2, N'Ocicat', NULL, 61, 0, N'اوسیکت', N'ocicat'),
(2, N'Peterbald', NULL, 62, 0, N'پیتربالد', N'peterbald'),
(2, N'Pixie-bob', NULL, 63, 0, N'پیکسی‌باب', N'pixie-bob'),
(2, N'Ragamuffin', NULL, 64, 0, N'رگامافین', N'ragamuffin'),
(2, N'Serengeti', NULL, 65, 0, N'سرنگتی', N'serengeti'),
(2, N'Singapura', NULL, 66, 0, N'سنگاپورا', N'singapura'),
(2, N'Snowshoe', NULL, 67, 0, N'اسنوشو', N'snowshoe'),
(2, N'Sokoke', NULL, 68, 0, N'سوکوکه', N'sokoke'),
(2, N'Somali', NULL, 69, 0, N'سومالی', N'somali-cat'),
(2, N'Toyger', NULL, 70, 0, N'تویگر', N'toyger'),
(2, N'Ukrainian Levkoy', NULL, 71, 0, N'اوکراینی لوکوی', N'ukrainian-levkoy'),
(2, N'York Chocolate', NULL, 72, 0, N'یورک چاکلت', N'york-chocolate'),
(2, N'Minuet', NULL, 73, 0, N'مینوئت (ناپلئون)', N'minuet');
GO
