USE [pastil_db]
GO
-- گونه‌های ماهی زینتی - ادامه‌ی لیست موجود (۲۶ گونه قبلی دست نخورده می‌مونه)

INSERT INTO [dbo].[PetBreeds] ([PetId], [Label], [PictureId], [Priority], [Deleted], [Name], [Slug]) VALUES
(3, N'Endler s Livebearer', NULL, 27, 0, N'اندلر', N'endlers-livebearer'),
(3, N'Cherry Barb', NULL, 28, 0, N'باربِ آلبالویی', N'cherry-barb'),
(3, N'Rosy Barb', NULL, 29, 0, N'باربِ صورتی', N'rosy-barb'),
(3, N'Black Skirt Tetra', NULL, 30, 0, N'تترای دامن‌سیاه', N'black-skirt-tetra'),
(3, N'Glowlight Tetra', NULL, 31, 0, N'تترای درخشان', N'glowlight-tetra'),
(3, N'Ember Tetra', NULL, 32, 0, N'تترای اِمبر', N'ember-tetra'),
(3, N'Rummy Nose Tetra', NULL, 33, 0, N'تترای بینی‌قرمز', N'rummy-nose-tetra'),
(3, N'Serpae Tetra', NULL, 34, 0, N'تترای سرپای', N'serpae-tetra'),
(3, N'Congo Tetra', NULL, 35, 0, N'تترای کنگو', N'congo-tetra'),
(3, N'Bristlenose Pleco', NULL, 36, 0, N'پلکوی بینی‌جارویی', N'bristlenose-pleco'),
(3, N'Otocinclus Catfish', NULL, 37, 0, N'گربه‌ماهی اوتوسینکلوس', N'otocinclus-catfish'),
(3, N'Kuhli Loach', NULL, 38, 0, N'لوچ کولی', N'kuhli-loach'),
(3, N'Yoyo Loach', NULL, 39, 0, N'لوچ یویو', N'yoyo-loach'),
(3, N'Dwarf Gourami', NULL, 40, 0, N'گورامی کوتوله', N'dwarf-gourami'),
(3, N'Pearl Gourami', NULL, 41, 0, N'گورامی مرواریدی', N'pearl-gourami'),
(3, N'Honey Gourami', NULL, 42, 0, N'گورامی عسلی', N'honey-gourami'),
(3, N'Kissing Gourami', NULL, 43, 0, N'گورامی بوسه‌ای', N'kissing-gourami'),
(3, N'Paradise Fish', NULL, 44, 0, N'ماهی بهشتی', N'paradise-fish'),
(3, N'Siamese Algae Eater', NULL, 45, 0, N'جلبک‌خوار سیامی', N'siamese-algae-eater'),
(3, N'Bala Shark', NULL, 46, 0, N'شارک بالا', N'bala-shark'),
(3, N'Silver Dollar Fish', NULL, 47, 0, N'ماهی سیلور دلار', N'silver-dollar-fish'),
(3, N'Red-Tailed Black Shark', NULL, 48, 0, N'شارک دم‌قرمز', N'red-tailed-black-shark'),
(3, N'Denison Barb', NULL, 49, 0, N'باربِ دنیسون', N'denison-barb'),
(3, N'Boesemani Rainbowfish', NULL, 50, 0, N'رینبوفیش بوسمنی', N'boesemani-rainbowfish'),
(3, N'Celestial Pearl Danio', NULL, 51, 0, N'دانیوی مرواریدی', N'celestial-pearl-danio'),
(3, N'White Cloud Mountain Minnow', NULL, 52, 0, N'مینوی کوه ابر سفید', N'white-cloud-mountain-minnow'),
(3, N'Oranda Goldfish', NULL, 53, 0, N'ماهی قرمز اوراندا', N'oranda-goldfish'),
(3, N'Ryukin Goldfish', NULL, 54, 0, N'ماهی قرمز ریوکین', N'ryukin-goldfish'),
(3, N'Ranchu Goldfish', NULL, 55, 0, N'ماهی قرمز رانچو', N'ranchu-goldfish'),
(3, N'Shubunkin Goldfish', NULL, 56, 0, N'ماهی قرمز شابانکین', N'shubunkin-goldfish'),
(3, N'Comet Goldfish', NULL, 57, 0, N'ماهی قرمز کامت', N'comet-goldfish'),
(3, N'Lionhead Goldfish', NULL, 58, 0, N'ماهی قرمز سر‌شیری', N'lionhead-goldfish'),
(3, N'Bubble Eye Goldfish', NULL, 59, 0, N'ماهی قرمز چشم‌حبابی', N'bubble-eye-goldfish'),
(3, N'Black Moor Goldfish', NULL, 60, 0, N'ماهی قرمز بلک‌مور', N'black-moor-goldfish'),
(3, N'Telescope Eye Goldfish', NULL, 61, 0, N'ماهی قرمز چشم‌تلسکوپی', N'telescope-eye-goldfish'),
(3, N'Jack Dempsey Cichlid', NULL, 62, 0, N'سیچلاید جک دمپسی', N'jack-dempsey-cichlid'),
(3, N'Firemouth Cichlid', NULL, 63, 0, N'سیچلاید دهان‌آتشی', N'firemouth-cichlid'),
(3, N'Convict Cichlid', NULL, 64, 0, N'سیچلاید زندانی', N'convict-cichlid'),
(3, N'Electric Yellow Cichlid', NULL, 65, 0, N'سیچلاید زرد الکتریکی', N'electric-yellow-cichlid'),
(3, N'Peacock Cichlid', NULL, 66, 0, N'سیچلاید طاووسی', N'peacock-cichlid'),
(3, N'Kribensis Cichlid', NULL, 67, 0, N'سیچلاید کریبنسیس', N'kribensis-cichlid'),
(3, N'Severum Cichlid', NULL, 68, 0, N'سیچلاید سوروم', N'severum-cichlid'),
(3, N'Blood Parrot Cichlid', NULL, 69, 0, N'سیچلاید طوطی خونی', N'blood-parrot-cichlid'),
(3, N'Texas Cichlid', NULL, 70, 0, N'سیچلاید تگزاسی', N'texas-cichlid'),
(3, N'Glass Catfish', NULL, 71, 0, N'گربه‌ماهی شیشه‌ای', N'glass-catfish'),
(3, N'Synodontis Catfish', NULL, 72, 0, N'گربه‌ماهی سینودونتیس', N'synodontis-catfish'),
(3, N'Upside-Down Catfish', NULL, 73, 0, N'گربه‌ماهی وارونه', N'upside-down-catfish'),
(3, N'Bumblebee Catfish', NULL, 74, 0, N'گربه‌ماهی زنبوری', N'bumblebee-catfish'),
(3, N'Iridescent Shark', NULL, 75, 0, N'شارک رنگین‌کمانی', N'iridescent-shark'),
(3, N'Asian Arowana', NULL, 76, 0, N'آروانای آسیایی', N'asian-arowana'),
(3, N'Halfmoon Betta', NULL, 77, 0, N'فایتر نیم‌ماه', N'halfmoon-betta'),
(3, N'Crowntail Betta', NULL, 78, 0, N'فایتر دم‌تاجی', N'crowntail-betta'),
(3, N'Blue Tang', NULL, 79, 0, N'تانگ آبی', N'blue-tang'),
(3, N'Yellow Tang', NULL, 80, 0, N'تانگ زرد', N'yellow-tang'),
(3, N'Royal Gramma', NULL, 81, 0, N'گرامای سلطنتی', N'royal-gramma'),
(3, N'Firefish Goby', NULL, 82, 0, N'گوبی ماهی‌آتشی', N'firefish-goby'),
(3, N'Mandarin Dragonet', NULL, 83, 0, N'ماندارین فیش', N'mandarin-dragonet'),
(3, N'Lionfish', NULL, 84, 0, N'ماهی شیری خاردار', N'lionfish'),
(3, N'Six Line Wrasse', NULL, 85, 0, N'راسی شش‌خط', N'six-line-wrasse'),
(3, N'Flame Angelfish', NULL, 86, 0, N'آنجل شعله‌ای', N'flame-angelfish'),
(3, N'Seahorse', NULL, 87, 0, N'اسب دریایی', N'seahorse'),
(3, N'Dwarf Puffer', NULL, 88, 0, N'پافر کوتوله', N'dwarf-puffer');
GO
