namespace Application.Common.Enumerable.Message
{
    public enum MessageTypeEnum
    {
        FreeText,
        Otp,
        ForgetPassword,
        ChangeEmail,
        ChangeMobile,
        UserRegisterOrder,
        AdminRegisterOrder,
        StoreRegisterOrder,
        AdminRegisterTicket,
        UserRegisterTicket,
        TicketAssignAdmin,
        TicketAnswerd,
        IncreaseWallet,
        UserSignUp,
        UserSignIn,
        UserLikeProduct,
        UserContactUs,
        AdminContactUs,
        TrackingCode,
        ProductOrderCancelRequest,
        ProductOrderCancelAnswer,
        ProductOrderReserve,
        UserReserveCompanion,
        UserChooseDriver,
        DriverRequest,
        DriverAccepted,
        UserReminderOneDayAgo,
        UserReminderOneWeekAgo,
        UserReminderTomorrow,
        CancelReserve,
        CompanionReserveForCompanion,
        CompanionReserveForCompanionUser,
        CompanionReserveForUser,
        CompanionReserveForAdmin,
        UserAcceptOperatorChange,
        AdminNotifyUserResponse,
        AdminNotifyTrip,
        CargoUser,
        CargoAdmin,
        RequestAllDrivers,
        DriverNotAcceptedYet,
        ProductOrderChangeStatus,
        PansionReserveForUser,
        PansionReserveForPansion,
        PansionReserveForAdmin,
        PansionReserveCancelForAdmin,
        // اضافه‌شده به انتهای enum عمداً؛ این enum به‌صورت ordinal تلویحی است و مقادیر قبلی نباید جابه‌جا شوند.
        UserReminderToday,
        // پیامک سبد خرید رها شده (الگوی کاوه‌نگار با همین نام: UserAbandonedCart)
        UserAbandonedCart,
        // پیامک ارسال سفارش: میاره (با کد تحویل) و پست (با شماره پیگیری)
        ProductOrderShippedMiare,
        ProductOrderShippedPost,
        // مشتری «تحویل گرفتم» زد: پیامک به ادمین و فروشنده؛ «تحویل نگرفتم»: پیامک به ادمین
        ProductOrderReceivedAdmin,
        ProductOrderReceivedStore,
        ProductOrderNotReceivedAdmin,
        // لغو کامل سفارش / کم یا حذف کردن کالا توسط ادمین یا فروشگاه (مبلغ به کیف پول مشتری برمی‌گردد)
        ProductOrderCancelledByAdminStore,
        ProductOrderCancelledByAdminUser,
        ProductOrderCancelledByStoreAdmin,
        ProductOrderCancelledByStoreUser,
        ProductOrderItemChangedByAdminStore,
        ProductOrderItemChangedByAdminUser,
        ProductOrderItemChangedByStoreUser
    }
}
